//! The Anvil-backed EVM engine: the [`Engine`] impl for a local EVM chain.
//!
//! Compose service YAML lives in `src/resources/docker/services/` and is
//! embedded into the binary at compile time — edit those templates, not Rust
//! strings.

use crate::runtime::engine::{Engine, ExplorerTarget, HealthProbe, StagedFile, StateMode};
use crate::runtime::manifest::{Account, ChainEntry, Contract, Token};

/// Internal port the engine listens on inside its container. The `INTERNAL_RPC`
/// that control/faucet reach it on is checked against this (see `session.rs`).
pub(crate) const ANVIL_INTERNAL_PORT: u16 = 8545;

/// How often Anvil flushes its state to disk in persistent mode. A small
/// interval keeps the on-disk session close to live so little is lost if the
/// process is killed rather than shut down gracefully.
const ANVIL_STATE_INTERVAL_SECS: u16 = 5;

/// Compose service template for an Anvil-backed EVM chain.
const ANVIL_SERVICE_TEMPLATE: &str = include_str!("../resources/docker/services/anvil.yml");

/// Pre-baked Anvil state snapshot with the test tokens deployed and seeded.
/// Generated by `scripts/gen-token-state.sh`. In ephemeral mode it is loaded
/// read-only via `--load-state`; in persistent mode a copy of it seeds the
/// chain's session snapshot the first time. Mounted under `./state/`.
const ANVIL_TOKEN_STATE: &str = include_str!("../resources/state/anvil-tokens.json");

/// Fork settings for an Anvil chain: mirror a live network's state from `url`,
/// optionally pinned to a block height.
struct Fork {
    url: String,
    block: Option<u64>,
}

impl Fork {
    /// A redacted description safe to record and print — the RPC key is dropped.
    fn describe(&self) -> String {
        crate::runtime::fork::describe(&self.url, self.block)
    }
}

/// An Anvil-backed EVM chain.
pub struct EvmEngine {
    name: String,
    image: String,
    host_port: u16,
    chain_id: u64,
    block_time: u64,
    fork: Option<Fork>,
}

impl EvmEngine {
    pub fn anvil(name: &str, host_port: u16, chain_id: u64) -> Self {
        EvmEngine {
            name: name.to_string(),
            image: "ghcr.io/foundry-rs/foundry:stable".to_string(),
            host_port,
            chain_id,
            block_time: 1,
            fork: None,
        }
    }

    /// Override the block time (auto-mining interval, in seconds).
    pub fn block_time(mut self, secs: u64) -> Self {
        self.block_time = secs;
        self
    }

    /// Fork this chain from a live RPC, optionally pinned to a block. A forked
    /// chain mirrors real network state, so it does not load the baked test
    /// tokens.
    pub fn fork(mut self, url: String, block: Option<u64>) -> Self {
        self.fork = Some(Fork { url, block });
        self
    }

    /// Whether this chain forks a live network.
    fn is_forked(&self) -> bool {
        self.fork.is_some()
    }

    /// Path (relative to the state dir) of this chain's persistent session
    /// snapshot. Per-chain because each chain has independent runtime state.
    fn session_rel_path(&self) -> String {
        format!("state/session-{}.json", self.name)
    }

    /// Test tokens pre-deployed in the loaded state snapshot. Deployed from dev
    /// account 0 at fixed nonces, so the addresses are deterministic and
    /// identical on every EVM chain. `mint` is public — the faucet relies on it.
    ///
    /// The first two are standard, well-behaved ERC-20s; the rest are
    /// deliberately "weird" (fee-on-transfer, rebasing, missing return value)
    /// for token-integration testing. See `resources/contracts/`.
    fn tokens() -> Vec<Token> {
        vec![
            Token {
                symbol: "USDC".to_string(),
                name: "USD Coin".to_string(),
                address: "0x5FbDB2315678afecb367f032d93F642f64180aa3".to_string(),
                decimals: 6,
            },
            Token {
                symbol: "WBTC".to_string(),
                name: "Wrapped BTC".to_string(),
                address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512".to_string(),
                decimals: 8,
            },
            Token {
                symbol: "FEE".to_string(),
                name: "Fee Token (fee-on-transfer)".to_string(),
                address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0".to_string(),
                decimals: 18,
            },
            Token {
                symbol: "REB".to_string(),
                name: "Rebasing Token".to_string(),
                address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9".to_string(),
                decimals: 18,
            },
            Token {
                symbol: "NRT".to_string(),
                name: "No Return Token (USDT-style)".to_string(),
                address: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9".to_string(),
                decimals: 6,
            },
        ]
    }

    /// Canonical infra contracts baked into the state snapshot at their real,
    /// chain-agnostic addresses — the same everywhere, so client libraries and
    /// deploy tooling that hardcode these addresses work out of the box.
    /// Multicall3 and Permit2 are etched from mainnet bytecode; the CREATE2
    /// deterministic deployer is deployed by Anvil itself.
    fn contracts() -> Vec<Contract> {
        vec![
            Contract {
                name: "Multicall3".to_string(),
                address: "0xcA11bde05977b3631167028862bE2a173976CA11".to_string(),
            },
            Contract {
                name: "Permit2".to_string(),
                address: "0x000000000022D473030F116dDEE9F6B43aC78BA3".to_string(),
            },
            Contract {
                name: "CREATE2 Deployer".to_string(),
                address: "0x4e59b44847b379578588920cA78FbF26c0B4956C".to_string(),
            },
        ]
    }

    /// Standard deterministic Anvil dev accounts (mnemonic:
    /// "test test test test test test test test test test test junk").
    /// These are well-known throwaway keys — safe to publish, never use with
    /// real funds.
    fn accounts() -> Vec<Account> {
        vec![
            Account {
                address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266".to_string(),
                private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
                    .to_string(),
                balance: "10000 ETH".to_string(),
            },
            Account {
                address: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8".to_string(),
                private_key: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
                    .to_string(),
                balance: "10000 ETH".to_string(),
            },
            Account {
                address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC".to_string(),
                private_key: "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
                    .to_string(),
                balance: "10000 ETH".to_string(),
            },
        ]
    }
}

impl Engine for EvmEngine {
    fn name(&self) -> String {
        self.name.clone()
    }

    fn host_port(&self) -> u16 {
        self.host_port
    }

    fn compose_service(&self, mode: StateMode) -> String {
        // A forked chain mirrors live state, so it never loads the baked token
        // snapshot. Ephemeral: load the baked tokens read-only (skipped when
        // forking), never dump. Persistent: `--state` loads the session snapshot
        // if present and dumps back to it on exit and every interval, so a
        // crash-restart resumes too — layered on top of the fork when forking.
        // Each arg group is leading-comma so it can collapse to nothing.
        let state_args = match (mode, self.is_forked()) {
            (StateMode::Ephemeral, true) => String::new(),
            (StateMode::Ephemeral, false) => {
                r#", "--load-state", "/state/anvil-tokens.json""#.to_string()
            }
            (StateMode::Persistent, _) => format!(
                r#", "--state", "/{session}", "--state-interval", "{interval}""#,
                session = self.session_rel_path(),
                interval = ANVIL_STATE_INTERVAL_SECS,
            ),
        };
        let fork_args = match &self.fork {
            None => String::new(),
            Some(fork) => {
                let mut a = format!(r#", "--fork-url", "{}""#, fork.url);
                if let Some(block) = fork.block {
                    a.push_str(&format!(r#", "--fork-block-number", "{block}""#));
                }
                a
            }
        };
        ANVIL_SERVICE_TEMPLATE
            .replace("{{NAME}}", &self.name)
            .replace("{{IMAGE}}", &self.image)
            .replace("{{PORT}}", &ANVIL_INTERNAL_PORT.to_string())
            .replace("{{CHAIN_ID}}", &self.chain_id.to_string())
            .replace("{{HOST_PORT}}", &self.host_port.to_string())
            .replace("{{BLOCK_TIME}}", &self.block_time.to_string())
            .replace("{{FORK_ARGS}}", &fork_args)
            .replace("{{STATE_ARGS}}", &state_args)
    }

    fn manifest_entry(&self) -> ChainEntry {
        // A forked chain mirrors live state; wharfnet deploys nothing onto it, so
        // it advertises no baked tokens or infra contracts — only the fork.
        let forked = self.is_forked();
        ChainEntry {
            name: self.name.clone(),
            kind: "evm".to_string(),
            rpc: format!("http://127.0.0.1:{}", self.host_port),
            chain_id: self.chain_id.to_string(),
            accounts: Self::accounts(),
            tokens: if forked { Vec::new() } else { Self::tokens() },
            contracts: if forked {
                Vec::new()
            } else {
                Self::contracts()
            },
            fork: self.fork.as_ref().map(Fork::describe),
            // Populated by the orchestrator when an explorer is booted.
            explorer: None,
        }
    }

    fn health_probe(&self) -> HealthProbe {
        // Anvil answers JSON-RPC; `eth_chainId` is the cheapest readiness ping.
        HealthProbe::JsonRpc {
            method: "eth_chainId",
        }
    }

    fn explorer_target(&self) -> Option<ExplorerTarget> {
        // Anvil implements the Otterscan RPC API (`ots_*`), so Otterscan works
        // against it with no indexer. The browser hits the published host port.
        Some(ExplorerTarget {
            chain_name: self.name.clone(),
            rpc_host_port: self.host_port,
        })
    }

    fn staged_files(&self, mode: StateMode) -> Vec<StagedFile> {
        // A forked chain loads no baked snapshot, so nothing to stage.
        if self.is_forked() {
            return Vec::new();
        }
        match mode {
            // Refreshed on every boot so the chain always starts from the
            // known-good pre-deployed tokens.
            StateMode::Ephemeral => vec![StagedFile {
                rel_path: "state/anvil-tokens.json".to_string(),
                contents: ANVIL_TOKEN_STATE,
                if_absent: false,
            }],
            // Seed the session with the baked tokens only the first time; on
            // later boots the existing session (with the user's work) is kept.
            StateMode::Persistent => vec![StagedFile {
                rel_path: self.session_rel_path(),
                contents: ANVIL_TOKEN_STATE,
                if_absent: true,
            }],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn anvil_constructor_sets_fields() {
        let e = EvmEngine::anvil("anvil-1", 8545, 31337);
        assert_eq!(e.name(), "anvil-1");
        assert_eq!(e.host_port(), 8545);
        assert_eq!(e.image, "ghcr.io/foundry-rs/foundry:stable");
        assert_eq!(e.chain_id, 31337);
    }

    #[test]
    fn compose_service_substitutes_every_placeholder() {
        for mode in [StateMode::Ephemeral, StateMode::Persistent] {
            let yaml = EvmEngine::anvil("anvil-2", 8546, 31338).compose_service(mode);
            assert!(yaml.contains("anvil-2:"));
            assert!(yaml.contains("ghcr.io/foundry-rs/foundry:stable"));
            assert!(yaml.contains("\"--chain-id\", \"31338\""));
            assert!(yaml.contains("\"8546:8545\""));
            assert!(!yaml.contains("{{"), "no placeholder should remain: {yaml}");
            assert!(!yaml.contains("}}"), "no placeholder should remain: {yaml}");
        }
    }

    #[test]
    fn ephemeral_compose_loads_baked_tokens_without_dumping() {
        let yaml = EvmEngine::anvil("anvil-1", 8545, 31337).compose_service(StateMode::Ephemeral);
        assert!(yaml.contains("\"--load-state\", \"/state/anvil-tokens.json\""));
        assert!(
            !yaml.contains("--state-interval"),
            "must not dump when ephemeral"
        );
        assert!(
            !yaml.contains("--dump-state"),
            "must not dump when ephemeral"
        );
        // The whole state dir is mounted so persistent runs can write dumps.
        assert!(yaml.contains("./state:/state"));
    }

    #[test]
    fn persistent_compose_loads_and_dumps_a_session_snapshot() {
        let yaml = EvmEngine::anvil("anvil-1", 8545, 31337).compose_service(StateMode::Persistent);
        assert!(yaml.contains("\"--state\", \"/state/session-anvil-1.json\""));
        assert!(yaml.contains("\"--state-interval\", \"5\""));
        // Uses --state (load+dump), not the ephemeral read-only load.
        assert!(
            !yaml.contains("--load-state"),
            "persistent uses --state, not --load-state"
        );
    }

    #[test]
    fn manifest_entry_describes_the_chain() {
        let entry = EvmEngine::anvil("anvil-1", 8545, 31337).manifest_entry();
        assert_eq!(entry.kind, "evm");
        assert_eq!(entry.rpc, "http://127.0.0.1:8545");
        assert_eq!(entry.chain_id, "31337");
        assert_eq!(entry.accounts.len(), 3);
        assert_eq!(
            entry.accounts[0].address,
            "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
        );
    }

    #[test]
    fn manifest_entry_lists_the_test_tokens() {
        let entry = EvmEngine::anvil("anvil-1", 8545, 31337).manifest_entry();
        let symbols: Vec<&str> = entry.tokens.iter().map(|t| t.symbol.as_str()).collect();
        assert_eq!(symbols, vec!["USDC", "WBTC", "FEE", "REB", "NRT"]);
        let usdc = &entry.tokens[0];
        assert_eq!(usdc.address, "0x5FbDB2315678afecb367f032d93F642f64180aa3");
        assert_eq!(usdc.decimals, 6);
        assert_eq!(entry.tokens[1].decimals, 8);
        // The weird tokens carry the addresses they deploy to at fixed nonces.
        assert_eq!(
            entry.tokens[2].address,
            "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
        );
        assert_eq!(entry.tokens[4].decimals, 6);
    }

    #[test]
    fn manifest_entry_lists_the_canonical_infra_contracts() {
        let entry = EvmEngine::anvil("anvil-1", 8545, 31337).manifest_entry();
        let names: Vec<&str> = entry.contracts.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["Multicall3", "Permit2", "CREATE2 Deployer"]);
        assert_eq!(
            entry.contracts[0].address,
            "0xcA11bde05977b3631167028862bE2a173976CA11"
        );
    }

    #[test]
    fn block_time_defaults_to_one_and_is_overridable() {
        let default =
            EvmEngine::anvil("anvil-1", 8545, 31337).compose_service(StateMode::Ephemeral);
        assert!(default.contains("\"--block-time\", \"1\""));

        let slow = EvmEngine::anvil("anvil-1", 8545, 31337)
            .block_time(12)
            .compose_service(StateMode::Ephemeral);
        assert!(slow.contains("\"--block-time\", \"12\""));
    }

    #[test]
    fn evm_chain_exposes_an_explorer_target_on_its_host_port() {
        let target = EvmEngine::anvil("anvil-2", 8546, 31338)
            .explorer_target()
            .expect("evm chains support an explorer");
        assert_eq!(target.chain_name, "anvil-2");
        assert_eq!(target.rpc_host_port, 8546);
    }

    #[test]
    fn ephemeral_staged_files_refresh_the_baked_snapshot() {
        let files = EvmEngine::anvil("anvil-1", 8545, 31337).staged_files(StateMode::Ephemeral);
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].rel_path, "state/anvil-tokens.json");
        assert!(!files[0].if_absent, "baked snapshot is always refreshed");
        // The snapshot really contains the deployed USDC contract.
        assert!(
            files[0]
                .contents
                .contains("5fbdb2315678afecb367f032d93f642f64180aa3")
        );
    }

    #[test]
    fn persistent_staged_files_seed_a_per_chain_session_only_if_absent() {
        let files = EvmEngine::anvil("anvil-2", 8546, 31338).staged_files(StateMode::Persistent);
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].rel_path, "state/session-anvil-2.json");
        assert!(files[0].if_absent, "must never clobber a saved session");
        assert!(
            files[0]
                .contents
                .contains("5fbdb2315678afecb367f032d93f642f64180aa3")
        );
    }

    #[test]
    fn forked_compose_adds_fork_url_and_skips_the_token_snapshot() {
        let yaml = EvmEngine::anvil("mainnet", 8545, 1)
            .fork("https://rpc.example/key".to_string(), Some(21_000_000))
            .compose_service(StateMode::Ephemeral);
        assert!(yaml.contains("\"--fork-url\", \"https://rpc.example/key\""));
        assert!(yaml.contains("\"--fork-block-number\", \"21000000\""));
        // A fork mirrors live state — it must not load the baked tokens.
        assert!(
            !yaml.contains("--load-state"),
            "forked chain must not load the token snapshot: {yaml}"
        );
        assert!(!yaml.contains("{{"), "no placeholder should remain: {yaml}");
    }

    #[test]
    fn forked_persistent_still_dumps_state_over_the_fork() {
        let yaml = EvmEngine::anvil("mainnet", 8545, 1)
            .fork("https://rpc.example/key".to_string(), None)
            .compose_service(StateMode::Persistent);
        assert!(yaml.contains("\"--fork-url\", \"https://rpc.example/key\""));
        assert!(!yaml.contains("--fork-block-number"), "no block was pinned");
        assert!(yaml.contains("\"--state\", \"/state/session-mainnet.json\""));
    }

    #[test]
    fn forked_chain_stages_no_files() {
        let engine = EvmEngine::anvil("mainnet", 8545, 1).fork("https://rpc/x".to_string(), None);
        assert!(engine.staged_files(StateMode::Ephemeral).is_empty());
        assert!(engine.staged_files(StateMode::Persistent).is_empty());
    }

    #[test]
    fn forked_manifest_entry_redacts_the_url_and_drops_baked_presets() {
        let entry = EvmEngine::anvil("mainnet", 8545, 1)
            .fork(
                "https://eth.example.com/v2/SECRET_KEY".to_string(),
                Some(123),
            )
            .manifest_entry();
        // The RPC key is never recorded.
        assert_eq!(
            entry.fork.as_deref(),
            Some("https://eth.example.com @ block 123")
        );
        // wharfnet deploys nothing onto a fork, so it advertises no presets.
        assert!(entry.tokens.is_empty());
        assert!(entry.contracts.is_empty());
    }
}
