//! The `starknet-devnet`-backed engine: the [`Engine`] impl for a local Starknet
//! chain.
//!
//! devnet predeploys its accounts and the ETH/STRK fee tokens itself,
//! deterministically from `--seed`. On top of that, wharfnet stages a baked
//! *replay log* (declares/deploys/mints the Cairo test tokens) that devnet
//! re-executes on boot — see [`STARKNET_TOKEN_STATE`]. The compose service YAML
//! lives in `src/resources/docker/services/` and is embedded at compile time.

use crate::runtime::engine::{Engine, HealthProbe, StagedFile, StateMode};
use crate::runtime::manifest::{Account, ChainEntry, Contract, Token};

/// Pinned devnet image. Pinned (like the Anvil and Otterscan images) so the
/// predeployed accounts and token addresses below stay reproducible. This tag
/// speaks JSON-RPC 0.10 (matching the `starknet-rust` client and public testnet).
const DEVNET_IMAGE: &str = "shardlabs/starknet-devnet-rs:0.9.1";

/// Port devnet listens on inside its container (its default).
const DEVNET_INTERNAL_PORT: u16 = 5050;

/// Fixed RNG seed, so the predeployed accounts are identical on every boot —
/// the Starknet analogue of Anvil's fixed dev mnemonic.
const DEVNET_SEED: u16 = 0;

/// Number of predeployed accounts (matches the three EVM dev accounts).
const DEVNET_ACCOUNTS: u16 = 3;

/// Resolved felt for devnet's default chain id (`TESTNET` → `SN_SEPOLIA`), as
/// returned by `starknet_chainId`. A felt, so it's carried as a string.
const SN_SEPOLIA: &str = "0x534e5f5345504f4c4941";

/// Compose service template for a `starknet-devnet` chain.
const STARKNET_SERVICE_TEMPLATE: &str = include_str!("../resources/docker/services/starknet.yml");

/// Path (relative to the state dir) of the baked token replay, mounted into the
/// container. devnet loads it on boot and re-executes it (declares/deploys/mints).
const TOKEN_STATE_REL_PATH: &str = "state/starknet-tokens.json";

/// Baked `starknet-devnet` replay log: declares the Cairo test-token classes,
/// deploys USDC/WBTC/FEE/REB at deterministic addresses, and seeds the dev
/// accounts. Generated by `scripts/gen-starknet-token-state.sh`; devnet replays
/// it on boot, so the tokens are present on every fresh chain. The addresses in
/// [`StarknetEngine::tokens`] are the deterministic deploy addresses from this log.
const STARKNET_TOKEN_STATE: &str = include_str!("../resources/state/starknet-tokens.json");

/// A `starknet-devnet`-backed Starknet chain.
pub struct StarknetEngine {
    name: String,
    image: String,
    host_port: u16,
    ui: bool,
}

impl StarknetEngine {
    pub fn devnet(name: &str, host_port: u16) -> Self {
        StarknetEngine {
            name: name.to_string(),
            image: DEVNET_IMAGE.to_string(),
            host_port,
            ui: false,
        }
    }

    /// Enable devnet's embedded web UI explorer (`--ui`), served at `/ui` on the
    /// chain's own RPC port. On by default under `up`; disabled by `up --bare`.
    /// Unlike the EVM chains — which pair with a separate Otterscan container —
    /// devnet serves its explorer in-process, so there's no extra service or
    /// host port to publish, and [`explorer_target`](Engine::explorer_target)
    /// stays `None` (Otterscan speaks the EVM-only `ots_*` API).
    pub fn ui(mut self, enabled: bool) -> Self {
        self.ui = enabled;
        self
    }

    /// URL of devnet's embedded web UI explorer for this chain, when enabled.
    /// The browser reaches it on the chain's published host port at `/ui`.
    fn explorer_url(&self) -> Option<String> {
        self.ui
            .then(|| format!("http://127.0.0.1:{}/ui", self.host_port))
    }

    /// Path (relative to the state dir) of this chain's persistent session
    /// replay. Per-chain, and named `session-…` so the orchestrator's reset and
    /// resume detection — which key off that prefix — treat it like any other
    /// saved session, no Starknet-specific handling required.
    fn session_rel_path(&self) -> String {
        format!("state/session-{}.json", self.name)
    }

    /// The deterministic predeployed accounts for `--seed 0`, captured from the
    /// pinned image. Addresses are the 0x + 64-hex canonical form; the docker
    /// e2e test asserts these still match devnet's `/predeployed_accounts`.
    /// Each is funded with 1000 ETH and 1000 STRK (10^21 wei/fri).
    fn accounts() -> Vec<Account> {
        [
            (
                "0x064b48806902a367c8598f4f95c305e8c1a1acba5f082d294a43793113115691",
                "0x0000000000000000000000000000000071d7bb07b9a64f6f78ac4c816aff4da9",
            ),
            (
                "0x078662e7352d062084b0010068b99288486c2d8b914f6e2a55ce945f8792c8b1",
                "0x000000000000000000000000000000000e1406455b7d66b1690803be066cbe5e",
            ),
            (
                "0x049dfb8ce986e21d354ac93ea65e6a11f639c1934ea253e5ff14ca62eca0f38e",
                "0x00000000000000000000000000000000a20a02f0ac53692d144b20cb371a60d7",
            ),
        ]
        .into_iter()
        .map(|(address, private_key)| Account {
            address: address.to_string(),
            private_key: private_key.to_string(),
            balance: "1000 ETH & 1000 STRK".to_string(),
        })
        .collect()
    }

    /// The tokens advertised for this chain: the baked Cairo test tokens
    /// (deployed by the replay log at these deterministic addresses, each with a
    /// public `mint` and seeded to the dev accounts) followed by devnet's own
    /// predeployed ETH/STRK fee tokens. The test-token addresses come from
    /// `scripts/gen-starknet-token-state.sh`; regenerating the replay updates them.
    ///
    /// The first two are standard, well-behaved ERC-20s; the next two are
    /// deliberately "weird" for token-integration testing (see
    /// `resources/contracts/starknet/`). Cairo's ERC-20 ABI returns `bool` by the
    /// standard, so the EVM stack's USDT-style no-return token has no analogue here.
    fn tokens() -> Vec<Token> {
        vec![
            Token {
                symbol: "USDC".to_string(),
                name: "USD Coin".to_string(),
                address: "0x040b582f9ba878be8e78a6ddc665dfdfd55a4deae9ceeb40115abcfa1f8df686"
                    .to_string(),
                decimals: 6,
            },
            Token {
                symbol: "WBTC".to_string(),
                name: "Wrapped BTC".to_string(),
                address: "0x029a79ea0c5716d63250a0bbf2462509f3c0eed9d29a2e1c02c63fa7b2b1db66"
                    .to_string(),
                decimals: 8,
            },
            Token {
                symbol: "FEE".to_string(),
                name: "Fee Token (fee-on-transfer)".to_string(),
                address: "0x07edc0e8738c7804ad087344c1c54d817f739dd4179f1dd4e11ea5badada47aa"
                    .to_string(),
                decimals: 18,
            },
            Token {
                symbol: "REB".to_string(),
                name: "Rebasing Token".to_string(),
                address: "0x06e94ed66ea18ea06a9bed118a8d6ebc3cc19d31ed025bd5abadd3477d300500"
                    .to_string(),
                decimals: 18,
            },
            Token {
                symbol: "ETH".to_string(),
                name: "Ether".to_string(),
                address: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
                    .to_string(),
                decimals: 18,
            },
            Token {
                symbol: "STRK".to_string(),
                name: "Starknet Token".to_string(),
                address: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"
                    .to_string(),
                decimals: 18,
            },
        ]
    }

    /// Canonical infra devnet predeploys at a fixed address: the Universal
    /// Deployer Contract, used for deterministic (CREATE2-style) deploys.
    fn contracts() -> Vec<Contract> {
        vec![Contract {
            name: "UDC".to_string(),
            address: "0x041a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf"
                .to_string(),
        }]
    }
}

impl Engine for StarknetEngine {
    fn name(&self) -> String {
        self.name.clone()
    }

    fn host_port(&self) -> u16 {
        self.host_port
    }

    fn compose_service(&self, mode: StateMode) -> String {
        // devnet's dump/load is a single `--dump-path` slot; whatever file it
        // points at is re-executed on boot. The `--dump-on` trigger decides
        // whether runtime changes are written back:
        //   * Ephemeral → `request`, which loads the baked replay but never writes
        //     it back (verified), so the chain stays disposable — and the file is
        //     re-staged fresh each boot anyway.
        //   * Persistent → `block`, which dumps after every block. Because devnet
        //     mines a block per transaction (its default), that continuously saves
        //     each tx to the per-chain session replay — the Starknet analogue of
        //     Anvil's `--state` — so work survives `docker stop` and `up --resume`
        //     with no explicit dump on teardown.
        let (dump_on, dump_path) = match mode {
            StateMode::Ephemeral => ("request", TOKEN_STATE_REL_PATH.to_string()),
            StateMode::Persistent => ("block", self.session_rel_path()),
        };
        let state_args = format!(r#", "--dump-on", "{dump_on}", "--dump-path", "/{dump_path}""#);
        // devnet serves the explorer in-process, so enabling it is a single flag
        // on the chain's own command — no companion container like the EVM chains.
        let ui_args = if self.ui { r#", "--ui""# } else { "" };
        STARKNET_SERVICE_TEMPLATE
            .replace("{{NAME}}", &self.name)
            .replace("{{IMAGE}}", &self.image)
            .replace("{{PORT}}", &DEVNET_INTERNAL_PORT.to_string())
            .replace("{{HOST_PORT}}", &self.host_port.to_string())
            .replace("{{SEED}}", &DEVNET_SEED.to_string())
            .replace("{{ACCOUNTS}}", &DEVNET_ACCOUNTS.to_string())
            .replace("{{STATE_ARGS}}", &state_args)
            .replace("{{UI_ARGS}}", ui_args)
    }

    fn manifest_entry(&self) -> ChainEntry {
        ChainEntry {
            name: self.name.clone(),
            kind: "starknet".to_string(),
            // devnet serves JSON-RPC at /rpc (and /).
            rpc: format!("http://127.0.0.1:{}/rpc", self.host_port),
            chain_id: SN_SEPOLIA.to_string(),
            accounts: Self::accounts(),
            tokens: Self::tokens(),
            contracts: Self::contracts(),
            fork: None,
            // devnet's own web UI, when `--ui` is on; no separate explorer service.
            explorer: self.explorer_url(),
        }
    }

    fn health_probe(&self) -> HealthProbe {
        // devnet exposes a plain HTTP liveness endpoint rather than eth_-style RPC.
        HealthProbe::HttpGet { path: "/is_alive" }
    }

    fn staged_files(&self, mode: StateMode) -> Vec<StagedFile> {
        match mode {
            // Refresh the baked token replay before every boot so an ephemeral
            // chain always starts from the known-good tokens (mirrors EvmEngine).
            StateMode::Ephemeral => vec![StagedFile {
                rel_path: TOKEN_STATE_REL_PATH.to_string(),
                contents: STARKNET_TOKEN_STATE,
                if_absent: false,
            }],
            // Seed the session replay from the baked tokens only the first time;
            // on later boots the existing session (the accumulated request log
            // that reconstructs the user's work) is kept untouched.
            StateMode::Persistent => vec![StagedFile {
                rel_path: self.session_rel_path(),
                contents: STARKNET_TOKEN_STATE,
                if_absent: true,
            }],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn devnet_constructor_sets_fields() {
        let e = StarknetEngine::devnet("starknet-1", 5050);
        assert_eq!(e.name(), "starknet-1");
        assert_eq!(e.host_port(), 5050);
        assert_eq!(e.image, DEVNET_IMAGE);
    }

    #[test]
    fn compose_service_substitutes_every_placeholder() {
        for mode in [StateMode::Ephemeral, StateMode::Persistent] {
            let yaml = StarknetEngine::devnet("starknet-1", 5055).compose_service(mode);
            assert!(yaml.contains("starknet-1:"));
            assert!(yaml.contains("shardlabs/starknet-devnet-rs:0.9.1"));
            assert!(yaml.contains("\"--seed\", \"0\""));
            assert!(yaml.contains("\"--accounts\", \"3\""));
            // Published host port maps to the container's 5050.
            assert!(yaml.contains("\"5055:5050\""));
            // Both modes load-and-replay via a `--dump-on`/`--dump-path` pair; the
            // specific trigger and file differ per mode (asserted separately).
            assert!(yaml.contains("\"--dump-on\","));
            assert!(yaml.contains("\"--dump-path\","));
            assert!(!yaml.contains("{{"), "no placeholder should remain: {yaml}");
            assert!(!yaml.contains("}}"), "no placeholder should remain: {yaml}");
        }
    }

    #[test]
    fn ephemeral_compose_loads_the_shared_token_replay_without_dumping() {
        let yaml = StarknetEngine::devnet("starknet-1", 5050).compose_service(StateMode::Ephemeral);
        // Ephemeral points the slot at the baked replay with `request`, which
        // loads it but never writes back, so runtime state stays disposable.
        assert!(yaml.contains("\"--dump-on\", \"request\""));
        assert!(yaml.contains("\"--dump-path\", \"/state/starknet-tokens.json\""));
        assert!(
            !yaml.contains("session-"),
            "ephemeral must not use a session"
        );
    }

    #[test]
    fn persistent_compose_dumps_each_block_to_a_per_chain_session() {
        let yaml =
            StarknetEngine::devnet("starknet-1", 5050).compose_service(StateMode::Persistent);
        // Persistent dumps on every block (= every tx) to a per-chain session
        // replay, so work accumulates across `down` → `up --resume`.
        assert!(yaml.contains("\"--dump-on\", \"block\""));
        assert!(yaml.contains("\"--dump-path\", \"/state/session-starknet-1.json\""));
        assert!(
            !yaml.contains("starknet-tokens.json"),
            "persistent uses the session file, not the shared baked replay"
        );
    }

    #[test]
    fn ui_enabled_adds_the_flag_and_advertises_the_in_process_explorer() {
        let e = StarknetEngine::devnet("starknet-1", 5050).ui(true);
        // The flag rides on devnet's own command (both state modes).
        for mode in [StateMode::Ephemeral, StateMode::Persistent] {
            assert!(e.compose_service(mode).contains("\"--ui\""));
        }
        // The manifest points at devnet's `/ui` on the chain's own host port —
        // no separate explorer service or port, unlike the EVM chains.
        assert_eq!(
            e.manifest_entry().explorer.as_deref(),
            Some("http://127.0.0.1:5050/ui")
        );
        // And it's an in-process explorer, so no Otterscan pairing is requested.
        assert!(e.explorer_target().is_none());
    }

    #[test]
    fn ui_disabled_by_default_omits_the_flag_and_the_explorer() {
        let e = StarknetEngine::devnet("starknet-1", 5050);
        // Check the quoted command token, not a bare substring — the template
        // comment mentions `--ui` even when the flag itself is absent.
        assert!(!e.compose_service(StateMode::Ephemeral).contains("\"--ui\""));
        assert!(e.manifest_entry().explorer.is_none());
    }

    #[test]
    fn manifest_entry_describes_the_chain() {
        let entry = StarknetEngine::devnet("starknet-1", 5050).manifest_entry();
        assert_eq!(entry.kind, "starknet");
        assert_eq!(entry.rpc, "http://127.0.0.1:5050/rpc");
        assert_eq!(entry.chain_id, "0x534e5f5345504f4c4941");
        assert_eq!(entry.accounts.len(), 3);
        assert_eq!(
            entry.accounts[0].address,
            "0x064b48806902a367c8598f4f95c305e8c1a1acba5f082d294a43793113115691"
        );
    }

    #[test]
    fn manifest_entry_lists_the_test_and_fee_tokens() {
        let entry = StarknetEngine::devnet("starknet-1", 5050).manifest_entry();
        let symbols: Vec<&str> = entry.tokens.iter().map(|t| t.symbol.as_str()).collect();
        assert_eq!(symbols, vec!["USDC", "WBTC", "FEE", "REB", "ETH", "STRK"]);
        // Standard tokens carry their real-world decimals; the rest are 18.
        let usdc = &entry.tokens[0];
        assert_eq!(usdc.decimals, 6);
        assert_eq!(
            usdc.address,
            "0x040b582f9ba878be8e78a6ddc665dfdfd55a4deae9ceeb40115abcfa1f8df686"
        );
        assert_eq!(entry.tokens[1].decimals, 8); // WBTC
        assert_eq!(entry.contracts[0].name, "UDC");
    }

    #[test]
    fn health_probe_is_the_is_alive_endpoint() {
        let probe = StarknetEngine::devnet("starknet-1", 5050).health_probe();
        assert!(matches!(probe, HealthProbe::HttpGet { path: "/is_alive" }));
    }

    #[test]
    fn ephemeral_stages_the_token_replay_and_has_no_explorer() {
        let e = StarknetEngine::devnet("starknet-1", 5050);
        let files = e.staged_files(StateMode::Ephemeral);
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].rel_path, "state/starknet-tokens.json");
        assert!(!files[0].if_absent, "baked replay is refreshed each boot");
        // The replay really declares/deploys the tokens (contains a declare tx).
        assert!(files[0].contents.contains("starknet_addDeclareTransaction"));
        assert!(e.explorer_target().is_none());
    }

    #[test]
    fn persistent_seeds_a_per_chain_session_only_if_absent() {
        let files = StarknetEngine::devnet("starknet-1", 5050).staged_files(StateMode::Persistent);
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].rel_path, "state/session-starknet-1.json");
        assert!(files[0].if_absent, "must never clobber a saved session");
        // Seeded from the baked replay, so a fresh session still has the tokens.
        assert!(files[0].contents.contains("starknet_addDeclareTransaction"));
    }

    // ---- docker-backed end-to-end run against a live starknet-devnet ----
    //
    // Boots a real devnet and checks the two facts the engine hardcodes: that
    // the liveness probe passes (so `up` really waited on the right endpoint),
    // and that the baked seed-0 accounts still match what devnet predeploys.
    // Self-skips without Docker.

    use crate::runtime::manifest::Manifest;
    use crate::runtime::orchestrator::manifest_path;
    use crate::testkit::{Localnet, docker_available};
    use std::collections::HashSet;
    use std::io::{Read, Write};
    use std::net::TcpStream;
    use std::time::Duration;

    /// A dedicated high port, away from the EVM e2e ports, so this can run in
    /// parallel with the other docker tests.
    const SN_E2E_PORT: u16 = 5150;

    /// Minimal HTTP GET → `(status_code, body)`.
    fn http_get(port: u16, path: &str) -> (u16, String) {
        let mut stream = TcpStream::connect(format!("127.0.0.1:{port}")).unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(5)))
            .unwrap();
        let req = format!("GET {path} HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n");
        stream.write_all(req.as_bytes()).unwrap();
        let mut resp = String::new();
        let _ = stream.read_to_string(&mut resp);
        let status = resp
            .split_whitespace()
            .nth(1)
            .and_then(|s| s.parse().ok())
            .unwrap_or(0);
        let body = resp.split("\r\n\r\n").nth(1).unwrap_or("").to_string();
        (status, body)
    }

    /// Minimal JSON-RPC POST to devnet's `/rpc` → raw response body.
    fn rpc(port: u16, body: &str) -> String {
        let mut stream = TcpStream::connect(format!("127.0.0.1:{port}")).unwrap();
        stream
            .set_read_timeout(Some(Duration::from_secs(5)))
            .unwrap();
        let req = format!(
            "POST /rpc HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
            body.len(),
            body
        );
        stream.write_all(req.as_bytes()).unwrap();
        let mut resp = String::new();
        let _ = stream.read_to_string(&mut resp);
        resp.split("\r\n\r\n").nth(1).unwrap_or("").to_string()
    }

    /// Normalize a felt for comparison: drop the `0x` and any leading zeros so
    /// devnet's minimal form matches the manifest's zero-padded form.
    fn norm(felt: &str) -> String {
        let h = felt.trim_start_matches("0x").trim_start_matches('0');
        if h.is_empty() {
            "0".into()
        } else {
            h.to_lowercase()
        }
    }

    #[test]
    fn starknet_devnet_boots_with_baked_accounts_and_tokens() {
        if !docker_available() {
            eprintln!("skipping starknet e2e: docker unavailable");
            return;
        }
        let net = Localnet::boot_starknet("t-starknet", SN_E2E_PORT);

        // Liveness: `up` only returns once /is_alive passed, but assert it
        // directly too — this is the endpoint the engine's health probe targets.
        let (status, body) = http_get(SN_E2E_PORT, "/is_alive");
        assert_eq!(status, 200, "GET /is_alive should be 200");
        assert!(body.contains("Alive"), "unexpected /is_alive body: {body}");

        // The manifest advertises the baked seed-0 accounts...
        let manifest = Manifest::read(&manifest_path(net.base())).unwrap();
        let chain = &manifest.chains[0];
        assert_eq!(chain.kind, "starknet");
        let baked: HashSet<String> = chain.accounts.iter().map(|a| norm(&a.address)).collect();

        // ...which must still match what devnet actually predeploys. On RPC 0.10
        // the predeployed-accounts cheat is a JSON-RPC method, not a REST route.
        let resp = rpc(
            SN_E2E_PORT,
            r#"{"jsonrpc":"2.0","id":1,"method":"devnet_getPredeployedAccounts","params":{}}"#,
        );
        let parsed: serde_json::Value = serde_json::from_str(&resp)
            .unwrap_or_else(|e| panic!("parsing devnet_getPredeployedAccounts '{resp}': {e}"));
        let live: HashSet<String> = parsed["result"]
            .as_array()
            .unwrap_or_else(|| panic!("no result array in {resp}"))
            .iter()
            .map(|a| norm(a["address"].as_str().unwrap()))
            .collect();
        assert_eq!(baked, live, "baked seed-0 accounts drifted from the image");

        // The baked replay must have declared+deployed each test token at its
        // hardcoded address — getClassHashAt returns a class hash (result) if a
        // contract lives there, or an error if not.
        for sym in ["USDC", "WBTC", "FEE", "REB"] {
            let token = chain
                .tokens
                .iter()
                .find(|t| t.symbol == sym)
                .unwrap_or_else(|| panic!("{sym} missing from manifest"));
            let body = format!(
                r#"{{"jsonrpc":"2.0","id":1,"method":"starknet_getClassHashAt","params":["latest","{}"]}}"#,
                token.address
            );
            let resp = rpc(SN_E2E_PORT, &body);
            assert!(
                resp.contains("\"result\""),
                "{sym} not deployed at {} (baked replay didn't load?): {resp}",
                token.address
            );
        }
    }

    /// A dedicated high port for the web-UI e2e, distinct from the other Starknet
    /// e2e ports so it can run in parallel.
    const SN_UI_E2E_PORT: u16 = 5154;

    #[test]
    fn starknet_devnet_serves_the_embedded_web_ui() {
        if !docker_available() {
            eprintln!("skipping starknet ui e2e: docker unavailable");
            return;
        }
        let net = Localnet::boot_starknet_ui("t-starknet-ui", SN_UI_E2E_PORT);

        // With `--ui` on, devnet serves its explorer in-process at /ui on the
        // chain's own RPC port — no companion container, no extra published port.
        let (status, body) = http_get(SN_UI_E2E_PORT, "/ui");
        assert_eq!(status, 200, "GET /ui should serve the embedded explorer");
        assert!(
            body.to_lowercase().contains("<!doctype html"),
            "GET /ui should return the explorer page, got: {}",
            &body[..body.len().min(200)]
        );

        // ...and the manifest advertises exactly that URL, so tooling can find it.
        let manifest = Manifest::read(&manifest_path(net.base())).unwrap();
        assert_eq!(
            manifest.chains[0].explorer.as_deref(),
            Some(format!("http://127.0.0.1:{SN_UI_E2E_PORT}/ui").as_str())
        );
    }
}
